USE [master]
GO

/****** Object:  Database [fookwit]    Script Date: 2020/12/21 11:49:29 ******/
CREATE DATABASE [fookwit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fookwit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\fookwit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fookwit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\fookwit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fookwit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fookwit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fookwit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fookwit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fookwit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fookwit] SET ARITHABORT OFF 
GO

ALTER DATABASE [fookwit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fookwit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fookwit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fookwit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fookwit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fookwit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fookwit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fookwit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fookwit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fookwit] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fookwit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fookwit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fookwit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fookwit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fookwit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fookwit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fookwit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fookwit] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [fookwit] SET  MULTI_USER 
GO

ALTER DATABASE [fookwit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fookwit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fookwit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fookwit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fookwit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fookwit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [fookwit] SET  READ_WRITE 
GO


